-- 코드를 입력하세요
WITH MAY_PRDT AS(
    SELECT PRODUCT_ID, AMOUNT FROM FOOD_ORDER
    WHERE PRODUCE_DATE LIKE "2022-05%"
)

SELECT MP.PRODUCT_ID,
       FP.PRODUCT_NAME,
       SUM(FP.PRICE * MP.AMOUNT) AS TOTAL_SALES
FROM MAY_PRDT AS MP
JOIN FOOD_PRODUCT AS FP
ON MP.PRODUCT_ID = FP.PRODUCT_ID
GROUP BY MP.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, MP.PRODUCT_ID;