-- 코드를 입력하세요
WITH MAX_PRICE AS (SELECT MAX(PRICE) AS PRICE FROM FOOD_PRODUCT)

SELECT PRODUCT_ID, PRODUCT_NAME, PRODUCT_CD, CATEGORY, PRICE
FROM FOOD_PRODUCT
WHERE PRICE = (SELECT PRICE FROM MAX_PRICE);