-- 코드를 입력하세요
WITH MOST_REVIEWER AS(
    SELECT MP.MEMBER_NAME,
           RR.MEMBER_ID
    FROM REST_REVIEW RR
    JOIN MEMBER_PROFILE MP
    ON RR.MEMBER_ID = MP.MEMBER_ID
    GROUP BY RR.MEMBER_ID
    ORDER BY COUNT(*) DESC
    LIMIT 1
)
    
SELECT MR.MEMBER_NAME,
       RR.REVIEW_TEXT,
       DATE_FORMAT(RR.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM REST_REVIEW AS RR
JOIN MOST_REVIEWER AS MR
ON RR.MEMBER_ID = MR.MEMBER_ID
ORDER BY REVIEW_DATE, REVIEW_TEXT;