-- 코드를 입력하세요
SELECT MONTH(START_DATE) AS MONTH,
       CAR_ID,
       COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY MONTH, CAR_ID
HAVING MONTH BETWEEN 8 AND 10
AND CAR_ID IN (
    SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE MONTH(START_DATE) BETWEEN 8 AND 10
    GROUP BY CAR_ID
    HAVING COUNT(CAR_ID) >= 5
)
AND RECORDS != 0
ORDER BY MONTH, CAR_ID DESC;

-- 코드를 입력하세요
WITH BIGGER_THAN_FIVE AS(
    SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE MONTH(START_DATE) BETWEEN 8 AND 10
    GROUP BY CAR_ID
    HAVING COUNT(CAR_ID) >= 5
)

SELECT MONTH(START_DATE) AS MONTH,
       CAR_ID,
       COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY MONTH, CAR_ID
HAVING MONTH BETWEEN 8 AND 10
AND CAR_ID IN (
    SELECT CAR_ID FROM BIGGER_THAN_FIVE
)
AND RECORDS != 0
ORDER BY MONTH, CAR_ID DESC;

-- 코드를 입력하세요
WITH BIGGER_THAN_FIVE AS(
    SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE MONTH(START_DATE) BETWEEN 8 AND 10
    GROUP BY CAR_ID
    HAVING COUNT(CAR_ID) >= 5
)

SELECT MONTH(START_DATE) AS MONTH,
       CAR_ID,
       COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE CAR_ID IN (
    SELECT CAR_ID FROM BIGGER_THAN_FIVE
)
GROUP BY MONTH, CAR_ID
HAVING MONTH BETWEEN 8 AND 10
AND RECORDS != 0
ORDER BY MONTH, CAR_ID DESC;

