-- 코드를 입력하세요
WITH INTACT AS (
    SELECT ANIMAL_ID
    FROM ANIMAL_INS
    WHERE SEX_UPON_INTAKE LIKE "Intact%"
)

SELECT ANIMAL_ID,
       ANIMAL_TYPE,
       NAME
FROM ANIMAL_OUTS
WHERE SEX_UPON_OUTCOME IN (
    'Spayed Female', 'Neutered Male'
)
AND ANIMAL_ID IN (SELECT ANIMAL_ID FROM INTACT)
ORDER BY ANIMAL_ID;

-- 코드를 입력하세요
SELECT OUTS.ANIMAL_ID,
       OUTS.ANIMAL_TYPE,
       OUTS.NAME
FROM ANIMAL_OUTS OUTS
RIGHT JOIN (
    SELECT ANIMAL_ID
    FROM ANIMAL_INS
    WHERE SEX_UPON_INTAKE LIKE "Intact%"
) INS
ON OUTS.ANIMAL_ID = INS.ANIMAL_ID
WHERE OUTS.SEX_UPON_OUTCOME LIKE "Spayed%"
OR OUTS.SEX_UPON_OUTCOME LIKE "Neutered%"
ORDER BY OUTS.ANIMAL_ID;