-- 코드를 입력하세요
WITH ID AS(
    SELECT USER_ID FROM USER_INFO
    WHERE JOINED LIKE '2021%'
)

, NUMS AS(
    SELECT COUNT(*) AS NUM_USERS FROM USER_INFO
    WHERE JOINED LIKE '2021%'
)

, PURC_USER AS(
    SELECT DISTINCT USER_ID, YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH
    FROM ONLINE_SALE
)
    
SELECT YEAR,
       MONTH,
       COUNT(*) AS PUCHASED_USERS,
       ROUND(
           COUNT(*) / (SELECT NUM_USERS FROM NUMS), 1
       ) AS PUCHASED_RATIO
FROM PURC_USER
WHERE USER_ID IN (SELECT USER_ID FROM ID)
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH;