-- 코드를 입력하세요
SELECT ANIMAL_ID,
       NAME
FROM ANIMAL_OUTS
WHERE ANIMAL_ID NOT IN (
    SELECT ANIMAL_ID FROM ANIMAL_INS
)
ORDER BY ANIMAL_ID, NAME;

-- 코드를 입력하세요
SELECT OUTS.ANIMAL_ID,
       OUTS.NAME
FROM ANIMAL_OUTS OUTS
LEFT OUTER JOIN ANIMAL_INS INS
ON OUTS.ANIMAL_ID = INS.ANIMAL_ID
WHERE INS.ANIMAL_ID is NULL
ORDER BY OUTS.ANIMAL_ID