-- 코드를 입력하세요
WITH VALUE AS (
    SELECT HISTORY_ID, CAR.DAILY_FEE, CAR.CAR_TYPE,
    DATEDIFF(end_date, start_date) + 1 AS PERIOD,
    CASE WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 90 THEN '90일 이상'
         WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 30 THEN '30일 이상'
         WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 7 THEN '7일 이상'
         ELSE NULL
         END AS DURATION
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS HISTORY
    JOIN CAR_RENTAL_COMPANY_CAR AS CAR
    ON HISTORY.CAR_ID = CAR.CAR_ID
    WHERE CAR.CAR_TYPE = '트럭'
)

SELECT VALUE.HISTORY_ID,
       ROUND(
           VALUE.DAILY_FEE * VALUE.PERIOD *
           (100 - IFNULL(PLAN.DISCOUNT_RATE, 0)) / 100
       ) AS FEE
FROM VALUE
LEFT OUTER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS PLAN
ON VALUE.DURATION = PLAN.DURATION_TYPE AND VALUE.CAR_TYPE = PLAN.CAR_TYPE
ORDER BY FEE DESC, VALUE.HISTORY_ID DESC;

/*
SQL WITH: https://cheershennah.tistory.com/203, https://schatz37.tistory.com/46
SQL IFNULL: https://velog.io/@gillog/DB-MySQL-NULL-%EC%B2%98%EB%A6%ACIFNULL-CASE-COALESCE
*/