-- 코드를 입력하세요
WITH BOOK_AUTHOR AS(
    SELECT BOOK.BOOK_ID, 
           BOOK.CATEGORY,
           BOOK.AUTHOR_ID,
           BOOK.PRICE,
           AUTHOR.AUTHOR_NAME
    FROM BOOK JOIN AUTHOR
    ON BOOK.AUTHOR_ID = AUTHOR.AUTHOR_ID
)

SELECT BA.AUTHOR_ID,
       BA.AUTHOR_NAME,
       BA.CATEGORY,
       SUM(BA.PRICE * SALES.SALES) AS TOTAL_SALES
FROM BOOK_SALES AS SALES
JOIN BOOK_AUTHOR AS BA
ON SALES.BOOK_ID = BA.BOOK_ID
WHERE DATE_FORMAT(SALES.SALES_DATE, '%Y-%m') = '2022-01'
GROUP BY BA.AUTHOR_ID, BA.CATEGORY
ORDER BY BA.AUTHOR_ID, BA.CATEGORY DESC;