-- 코드를 입력하세요
SELECT BOARD.TITLE, 
       BOARD.BOARD_ID,
       REPLY.REPLY_ID,
       REPLY.WRITER_ID, 
       REPLY.CONTENTS, 
       DATE_FORMAT(REPLY.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
FROM USED_GOODS_BOARD AS BOARD 
INNER JOIN USED_GOODS_REPLY AS REPLY
ON BOARD.BOARD_ID = REPLY.BOARD_ID
WHERE BOARD.CREATED_DATE BETWEEN '2022-10-01' AND '2022-10-31'
ORDER BY REPLY.CREATED_DATE, BOARD.TITLE;

--
SELECT BOARD.TITLE, 
       BOARD.BOARD_ID,
       REPLY.REPLY_ID,
       REPLY.WRITER_ID, 
       REPLY.CONTENTS, 
       DATE_FORMAT(REPLY.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
FROM USED_GOODS_BOARD AS BOARD 
INNER JOIN USED_GOODS_REPLY AS REPLY
ON BOARD.BOARD_ID = REPLY.BOARD_ID
WHERE SUBSTR(BOARD.CREATED_DATE, 1, 7) = '2022-10'
ORDER BY REPLY.CREATED_DATE, BOARD.TITLE;

/*
날짜 포멧 확인: https://velog.io/@donghoim/MySQL-DATETIME-%EC%9B%90%ED%95%98%EB%8A%94-%EC%9C%A0%ED%98%95%EC%9C%BC%EB%A1%9C-%EB%B3%80%EA%B2%BD-YYMMDD
날짜 조건식: https://chragu.com/entry/MySQL-SELECT-DATE
SQL 조인 조건: https://doh-an.tistory.com/30
SQL 기본 문법: https://rachel0115.tistory.com/entry/SQL-%EA%B8%B0%EB%B3%B8-%EB%AC%B8%EB%B2%95-%EC%A0%95%EB%A6%AC-SELECT-%EC%A0%88
*/

