-- 코드를 입력하세요
SELECT CONCAT(
    '/home/grep/src', '/', 
    BOARD.BOARD_ID, '/', 
    FILE.FILE_ID, FILE.FILE_NAME, FILE.FILE_EXT
    ) AS FILE_PATH
FROM USED_GOODS_BOARD AS BOARD
RIGHT OUTER JOIN USED_GOODS_FILE AS FILE
ON BOARD.BOARD_ID = FILE.BOARD_ID
WHERE BOARD.VIEWS = (SELECT MAX(VIEWS) FROM USED_GOODS_BOARD)
ORDER BY FILE.FILE_ID DESC;

-- 문자열 합치기: https://lcs1245.tistory.com/entry/SQL-%EB%AC%B8%EC%9E%90-%ED%95%A9%EC%B9%98%EA%B8%B0-%EC%8C%8D%ED%8C%8C%EC%9D%B4%ED%94%84-CONCAT